### ISSUE TITLE
Config Phyton Error

### ISSUE THREAD

**Issue by mksmks1** [small-cactus/M.I.L.E.S#16]
**Describe the bug**
 after finishing all my installation processes I started M.I.L.E.S but after starting I got an error called config phyton errors but I couldn't figure out what the error was caused by 

**To Reproduce**
1. Set up M.I.L.E.S.
2. Run to M.I.L.E.S.
3. Enter your details

**Expected behavior**
the programme runs without error

**Screenshots**
<img width="1438" alt="Ekran Resmi 2024-04-24 12 12 49" src="https://github.com/small-cactus/M.I.L.E.S/assets/77492965/6ab14f37-0db1-4b0a-be94-ffbe3464ec0d">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 14.2.1 (23C71)

**Additional context**

**Comment by small-cactus** [comment]
Hello! The error is occurring because Python can't find the module for openwakeword.

Ensure you installed requirements.txt using the instructions below (it's not a required step for Mac, but we can try it anyways). If you already did, run the setup script again. Here's how to install requirements:

```bash
pip install -r requirements.txt
```

If that still doesn't work, try using pip3 instead of pip.

Make sure you followed the instructions correctly, if you don't have a virtual environment set up like outlined in the instructions, it won't work.

Let me know if this fixed your issue.

**Comment by mksmks1** [comment]
Python Output: [Miles is Wake word models downloaded...]

Python Output: [Miles is Downloading speech recognition models...]

Python Output: [Miles is Base model downloaded successfully...]

Python Output: [Miles is Downloading tiny model...]

Python Output: [Miles is Tiny model downloaded successfully...]

Python Output: [Miles is Ready for speech, try saying 'this is a test']

Python Output: Switching to tiny model due to: Transcription took longer than 3 seconds with the base model.

Python Output: [Miles is You said:  Zuschelter.]

Python Output: [Miles is Config Complete!]

Config script exited with code 0

this time I encountered such a problem

**Comment by small-cactus** [comment]
That's normal behavior. It should continue after that script ends. Are you sure you're running the right file? You shouldn't be running the config file directly.

**Comment by mksmks1** [comment]
but when I reboot everything starts all over again and I install everything again

**Comment by small-cactus** [comment]
Try running:

npm start

Make sure you're Inside the directory

Copy and paste the terminal output once the issue occurs, I need the whole output from the start where you typed npm start to the end.

**Comment by williamblake333** [comment]
![image](https://github.com/small-cactus/M.I.L.E.S/assets/166770665/a466d4d8-52c4-400a-a3ec-5dae0589ba6e)

Hi there. I'm getting the above.

I've gone through the setup five or six times. It says API keys are empty but I've input them.

I checked the apikey.py file and my configuration is saved there, however the electron application isn't recognizing that I've already completed the setup.

**Comment by small-cactus** [comment]
That's odd, the config file doesn't save anything, it just downloads missing files. 

It saying empty means you have at least one api key set to "empty".

Also since you got it fixed, if responses are slow, open main.py and search for "base" change it to "tiny".

**Comment by williamblake333** [comment]
ok maybe it was just a fluke then. odd!
