### ISSUE TITLE
Cli Support 

### ISSUE THREAD

**Issue by developerSWe4b** [small-cactus/M.I.L.E.S#20]
Could you please add a cli support

**Comment by developerSWe4b** [comment]
I mean I need the to run the application in command line interface and interact with its

**Comment by developerSWe4b** [comment]
in simple terms, I want the application to be run on linux server without using gui

**Comment by small-cactus** [comment]
The entire app can be run without the GUI, if you pre place the apikeys in the apikey.py file and run the config script manually from terminal, then the script can run by itself. It’ll still be voice controlled tho.

**Comment by developerSWe4b** [comment]
> The entire app can be run without the GUI, if you pre place the apikeys in the apikey.py file and run the config script manually from terminal, then the script can run by itself. It’ll still be voice controlled tho.

Ok thanks I would try

**Comment by developerSWe4b** [comment]
So I just need to place the APIs keys and run the script?

**Comment by Danieljes** [comment]
sorry i intrude more how i enable Miles' voice interface or better projection ui with sound as I did all the windows tutorial plus mine doesn't work

**Comment by small-cactus** [comment]
Projection UI can be enabled if you rename the files with “projection” in the name to the name without projection in the name, then rename the other ones to something else.

indexProjection.js 

would become

index.js


If you could share logs as to why it doesn’t work from the terminal that would be great, make sure you followed the tutorial and restarted your pc when asked.
