### ISSUE TITLE
Doesn't listen the mic

### ISSUE THREAD

**Issue by VikFinlay** [small-cactus/M.I.L.E.S#22]
No way to let it recognize the mic.
"Listening for 'Miles'" stays there flashing forever.
Program correctly installed on Windows 11, i think: i followed all instructions, no errors, APi keys inserted and program is up and running.
I have 3 mics: external, notebook and webcam. I tried all of them, all of them are working (i'm a streamer and use it everyday) but none is recognized or listened by Miles.
Suggestions?

**Comment by small-cactus** [comment]
It uses whichever is set as your default communications device in control panel. If you have a thick accent, or theres a lot of background noise, Miles may not be able to hear you say his name. Try Nvidia broadcast as a last resort.

1. Open Control Panel:
   - Press Win + R to open the Run dialog.
   - Type control and press Enter to open the Control Panel.

2. Navigate to Sound Settings:
   - In the Control Panel, select Hardware and Sound.
   - Click on Sound to open the Sound settings window.

3. Select the Playback Tab:
   - In the Sound settings window, go to the Playback tab. This tab lists all the playback devices connected to your computer.

4. Set Default Communication Device:
   - Right-click on the device you want to set as the default communication device.
   - From the context menu, select Set as Default Communication Device.
   - A green phone icon will appear next to the selected device, indicating it is now the default communication device.

5. Confirm and Apply Changes:
   - Click Apply and then OK to confirm and close the Sound settings window.

**Comment by b3ta1911** [comment]
Hi again,

I have tried this on my PC. I had some better luck but the i cant get the voice to work.
I followed all your steps. 

![image](https://github.com/user-attachments/assets/ed2a72c2-b99f-4077-9209-8ae4e6d1dd9b)
![image](https://github.com/user-attachments/assets/7f917203-b58a-46a0-8e83-1566ca136c73)
![image](https://github.com/user-attachments/assets/0784ec9d-9ce5-4710-910e-2a8e17bcc498)
![image](https://github.com/user-attachments/assets/1d2be1be-29c4-4903-a2e0-ba6c55843cea)

But it still don't work. Do you have any suggestions?
