### ISSUE TITLE
Fix Code Execution

### ISSUE THREAD

**Issue by jxfzzzt** [small-cactus/M.I.L.E.S#27]
**Describe the bug**
Hello, i find a vulnerability in `Miles-V2/main.py` file.
The method `set_system_volume` may cause code execution vulnerability.

**To Reproduce**
volume_level = "20' && cat /etc/passwd && echo '$PATH" https://github.com/small-cactus/M.I.L.E.S/pull/25

**Vulnerable behavior**
```
[Miles is setting system volume to 20' && cat /etc/passwd && echo '$PATH%...]
##
nobody:*:**-2:Unprivileged User:/va*****ty:/usr/bin/false
root:*:***:System Admi****rator:/var/ro*****in/sh
daemon:*:***1:System Services:/var/root:/****bin/false
......
$PATH
{"System Volume Success Message": "System volume set to 20' && cat /etc/passwd && echo '$PATH"}
```

**Screenshots**

**Desktop**
 - OS: [Mac]

**Comment by small-cactus** [comment]
Miles does not have a keyboard capable interface, it is speech only, this command is only accessible by Miles himself. Miles can only provide a string to change volume. You would have to edit the python to manually append the rest of the command to each volume request.


TLDR: You need to edit the code manually for this vulnerability to affect users. If you have the capability to edit the code and run it, you have the capability to manually run the command yourself. Won't fix.
