### ISSUE TITLE
Error Loading melspectrogram.onnx with ONNX Runtime in M.I.L.E.S Project

### ISSUE THREAD

**Issue by jplantenga** [small-cactus/M.I.L.E.S#6]
I encountered a runtime error when trying to initialize the OpenWakeWord model in the M.I.L.E.S project. The specific error is related to loading the melspectrogram.onnx file using ONNX runtime, which fails due to the file not being found.

Steps ive made:
- Start the M.I.L.E.S Node.js server.
- The Python backend attempts to initialize.
- The error occurs during the OpenWakeWord model initialization.

Error Behavior:
Received NoSuchFile error from ONNXRuntime indicating that the melspectrogram.onnx file does not exist in the specified directory. But dependency openwakeword is properly installed.

Environment:
OS: macOS
Python version: 3.11

Additional Context:
The setup went fine, ive had the opportunity to enter API's for OpenAI, Spotify. When I clicked "Start Downloads" this is where the setup didn't show progress anymore and errors showed in the terminal (missing dependencies, ive installed these manually later) starting MILES every time every time to see which dependency was missing.. with every dependency installed ive encountered this error. Ive included the terminal process (its more than one line > scroll down).
[Terminal output error onnx.txt](https://github.com/small-cactus/M.I.L.E.S/files/14775996/Terminal.output.error.onnx.txt)

Hoping to hear back from you so I can fix this.

**Comment by small-cactus** [comment]
That’s weird that dependencies didn’t install correctly, I’ve been having
the same issue for windows users, strangely it works fine for me everytime
I test it, but the issue is you need to manually run the config file again,
so run the command (in the directory):

python3 config.py

**Comment by jplantenga** [comment]
It reinstalled the dependencies but you can see it still doesn't quite run as it should. Although it does give the output "Listening for Miles". But the Electron/Miles UI shows "Error Please restart MILES"

Last login: Wed Mar 27 16:30:11 on ttys001
You have new mail.
beheerder@macbook-john ~ % python main.py
zsh: command not found: python
beheerder@macbook-john ~ % source ~/Miles-env/bin/activate
(Miles-env) beheerder@macbook-john ~ % cd ~/Miles-env/M.I.L.E.S/Miles-V2
(Miles-env) beheerder@macbook-john Miles-V2 % python3 config.py
[Miles is Downloading wake word model...]
embedding_model.tflite: 100%|██████████████| 1.33M/1.33M [00:00<00:00, 256MiB/s]
embedding_model.onnx: 100%|███████████████| 1.33M/1.33M [00:00<00:00, 14.9MiB/s]
melspectrogram.tflite: 100%|██████████████| 1.09M/1.09M [00:00<00:00, 12.9MiB/s]
melspectrogram.onnx: 100%|████████████████| 1.09M/1.09M [00:00<00:00, 12.2MiB/s]
silero_vad.onnx: 100%|████████████████████| 1.81M/1.81M [00:00<00:00, 15.4MiB/s]
alexa_v0.1.tflite: 100%|████████████████████| 855k/855k [00:00<00:00, 12.1MiB/s]
alexa_v0.1.onnx: 100%|██████████████████████| 854k/854k [00:00<00:00, 12.3MiB/s]
hey_mycroft_v0.1.tflite: 100%|████████████████████████████████| 860k/860k [00:00<00:00, 10.2MiB/s]
hey_mycroft_v0.1.onnx: 100%|██████████████████████████████████| 858k/858k [00:00<00:00, 9.12MiB/s]
hey_jarvis_v0.1.tflite: 100%|███████████████████████████████| 1.28M/1.28M [00:00<00:00, 12.4MiB/s]
hey_jarvis_v0.1.onnx: 100%|█████████████████████████████████| 1.27M/1.27M [00:00<00:00, 12.5MiB/s]
hey_rhasspy_v0.1.tflite: 100%|████████████████████████████████| 416k/416k [00:00<00:00, 7.96MiB/s]
hey_rhasspy_v0.1.onnx: 100%|██████████████████████████████████| 204k/204k [00:00<00:00, 5.60MiB/s]
timer_v0.1.tflite: 100%|████████████████████████████████████| 1.74M/1.74M [00:00<00:00, 14.6MiB/s]
timer_v0.1.onnx: 100%|██████████████████████████████████████| 1.74M/1.74M [00:00<00:00, 13.4MiB/s]
weather_v0.1.tflite: 100%|██████████████████████████████████| 1.15M/1.15M [00:00<00:00, 11.3MiB/s]
weather_v0.1.onnx: 100%|████████████████████████████████████| 1.15M/1.15M [00:00<00:00, 7.50MiB/s]
[Miles is Wake word models downloaded...]
[Miles is Downloading speech recognition models...]
Traceback (most recent call last):
  File "/Users/beheerder/Miles-env/M.I.L.E.S/Miles-V2/config.py", line 28, in <module>
    whisper.load_model("base")
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'whisper' has no attribute 'load_model'
(Miles-env) beheerder@macbook-john Miles-V2 % ip install --upgrade whisper
zsh: command not found: ip
(Miles-env) beheerder@macbook-john Miles-V2 % pip install --upgrade whisper
Requirement already satisfied: whisper in /Users/beheerder/Miles-env/lib/python3.11/site-packages (1.1.10)
Requirement already satisfied: six in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from whisper) (1.16.0)
(Miles-env) beheerder@macbook-john Miles-V2 % npm start

> m.i.l.e.s@2.0.0 start
> electron .

Server started on http://localhost:3000
2024-03-27 17:15:29.860 Electron[7887:98380] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
API keys are set, starting server and backend...
Server is already running on port 3000
Python Error: /Users/beheerder/Miles-env/M.I.L.E.S/Miles-V2/main.py:1: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  from cgi import print_directory

Python Output: User is on macOS, using tflite model.

Python Error: WARNING:root:Tried to import the tflite runtime, but it was not found. Trying to switching to onnxruntime instead, if appropriate models are available.

Python Output: Listening for 'Miles'...

Python script exited with code: null
(Miles-env) beheerder@macbook-john Miles-V2 %

**Comment by small-cactus** [comment]
On my Mac I had to install everything with pip3 rather than pip, also try
to upgrade whisper with openai-whisper instead of just whisper.

**Comment by jplantenga** [comment]
After reinstalling, upgrading whisper to openai-whisper and making sure all is done with pip3 instead of pip.
I still am not able to get this working because of errors (and missing files) in the openwakeword repo.

Despite these efforts, the core issue appears to be with the openwakeword package, particularly missing model files necessary for operation. The logs indicate that the system attempts to switch from tflite to onnxruntime due to missing files, but then encounters a critical error due to the absence of the melspectrogram.onnx model. 

I do not see a possibility to fix this myself. I can see as soon as the script is running the first the config.py does not include all the right files for the install.

Can you help me out especially with the file it keeps saying is missing?

The following terminal log I have:

Last login: Wed Mar 27 23:00:57 on ttys000
You have new mail.
beheerder@MacBook-Pro ~ % source ~/Miles-env/bin/activate  
(Miles-env) beheerder@MacBook-Pro ~ % cd ~/Miles-env/M.I.L.E.S/Miles-V2
(Miles-env) beheerder@MacBook-Pro Miles-V2 % npm start                        

> m.i.l.e.s@2.0.0 start
> electron .

Server started on http://localhost:3000
2024-03-27 23:03:14.355 Electron[13032:225317] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
API keys are set, starting server and backend...
Server is already running on port 3000
Python Error: /Users/beheerder/Miles-env/M.I.L.E.S/Miles-V2/main.py:1: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  from cgi import print_directory

Python Output: User is on macOS, using tflite model.

Python Error: WARNING:root:Tried to import the tflite runtime, but it was not found. Trying to switching to onnxruntime instead, if appropriate models are available.

Python Error: Traceback (most recent call last):
  File "/Users/beheerder/Miles-env/M.I.L.E.S/Miles-V2/main.py", line 1308, in <module>

Python Error:     main()
  File "/Users/beheerder/Miles-env/M.I.L.E.S/Miles-V2/main.py", line 1238, in main

Python Error:     owwModel = initialize_wake_word_model()
               ^^^^^^^^^^
Python Error: ^^^^^^^^^^^^^^^^^^
  File "/Users/beheerder/Miles-env/M.I.L.E.S/Miles-V2/main.py", line 1229, in initialize_wake_word_model

Python Error:     owwModel = Model(wakeword_models=[MODEL_PATH], inference_framework=INFERENCE_FRAMEWORK)
   
Python Error:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beheerder/Miles-env/lib/python3.11/site-packages/openwakeword/utils.py", line 686, in wrapped
    return func(*args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beheerder/Miles-env/lib/python3.11/site-packages/openwakeword/model.py", line 213, in __init__

Python Error:     self.preprocessor = AudioFeatures(inference_framework=inference_framework, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beheerder/Miles-env/lib/python3.11/site-packages/openwakeword/utils.py", line 84, in __init__
    self.melspec_model = ort.InferenceSession(melspec_model_path, sess_options=sessionOptions,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Python Error: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beheerder/Miles-env/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/Users/beheerder/Miles-env/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session

Python Error:     sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Python Error: ^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /Users/beheerder/Miles-env/lib/python3.11/site-packages/openwakeword/resources/models/melspectrogram.onnx failed:Load model /Users/beheerder/Miles-env/lib/python3.11/site-packages/openwakeword/resources/models/melspectrogram.onnx failed. File doesn't exist

Python script exited with code: 1
(Miles-env) beheerder@MacBook-Pro Miles-V2 % pip3 install openwakeword
DEPRECATION: Loading egg at /Users/beheerder/Miles-env/lib/python3.11/site-packages/openwakeword-0.6.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: openwakeword in /Users/beheerder/Miles-env/lib/python3.11/site-packages/openwakeword-0.6.0-py3.11.egg (0.6.0)
Requirement already satisfied: onnxruntime<2,>=1.10.0 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from openwakeword) (1.17.1)
Requirement already satisfied: tqdm<5.0,>=4.0 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from openwakeword) (4.66.2)
Requirement already satisfied: scipy<2,>=1.3 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from openwakeword) (1.12.0)
Requirement already satisfied: scikit-learn<2,>=1 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from openwakeword) (1.4.1.post1)
Requirement already satisfied: requests<3,>=2.0 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from openwakeword) (2.31.0)
Requirement already satisfied: coloredlogs in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from onnxruntime<2,>=1.10.0->openwakeword) (15.0.1)
Requirement already satisfied: flatbuffers in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from onnxruntime<2,>=1.10.0->openwakeword) (24.3.25)
Requirement already satisfied: numpy>=1.24.2 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from onnxruntime<2,>=1.10.0->openwakeword) (1.26.4)
Requirement already satisfied: packaging in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from onnxruntime<2,>=1.10.0->openwakeword) (24.0)
Requirement already satisfied: protobuf in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from onnxruntime<2,>=1.10.0->openwakeword) (5.26.1)
Requirement already satisfied: sympy in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from onnxruntime<2,>=1.10.0->openwakeword) (1.12)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from requests<3,>=2.0->openwakeword) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from requests<3,>=2.0->openwakeword) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from requests<3,>=2.0->openwakeword) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from requests<3,>=2.0->openwakeword) (2024.2.2)
Requirement already satisfied: joblib>=1.2.0 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from scikit-learn<2,>=1->openwakeword) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from scikit-learn<2,>=1->openwakeword) (3.4.0)
Requirement already satisfied: humanfriendly>=9.1 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from coloredlogs->onnxruntime<2,>=1.10.0->openwakeword) (10.0)
Requirement already satisfied: mpmath>=0.19 in /Users/beheerder/Miles-env/lib/python3.11/site-packages (from sympy->onnxruntime<2,>=1.10.0->openwakeword) (1.3.0)
(Miles-env) beheerder@MacBook-Pro Miles-V2 % npm start                

> m.i.l.e.s@2.0.0 start
> electron .

Server started on http://localhost:3000
2024-03-27 23:03:30.114 Electron[13063:225783] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
API keys are set, starting server and backend...
Server is already running on port 3000
Python Error: /Users/beheerder/Miles-env/M.I.L.E.S/Miles-V2/main.py:1: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  from cgi import print_directory

Python Output: User is on macOS, using tflite model.

Python Error: WARNING:root:Tried to import the tflite runtime, but it was not found. Trying to switching to onnxruntime instead, if appropriate models are available.

Python Error: Traceback (most recent call last):
  File "/Users/beheerder/Miles-env/M.I.L.E.S/Miles-V2/main.py", line 1308, in <module>

Python Error:     main()
  File "/Users/beheerder/Miles-env/M.I.L.E.S/Miles-V2/main.py", line 1238, in main

Python Error:     owwModel = initialize_wake_word_model()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
Python Error: ^^^
  File "/Users/beheerder/Miles-env/M.I.L.E.S/Miles-V2/main.py", line 1229, in initialize_wake_word_model

Python Error:     owwModel = Model(wakeword_models=[MODEL_PATH], inference_framework=INFERENCE_FRAMEWORK)
  
Python Error:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beheerder/Miles-env/lib/python3.11/site-packages/openwakeword/utils.py", line 686, in wrapped

Python Error:     return func(*args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beheerder/Miles-env/lib/python3.11/site-packages/openwakeword/model.py", line 213, in __init__
    self.preprocessor = AudioFeatures(inference_framework=inference_framework, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Python Error: ^^^^^^^^^^^^
  File "/Users/beheerder/Miles-env/lib/python3.11/site-packages/openwakeword/utils.py", line 84, in __init__
    self.melspec_model = ort.InferenceSession(melspec_model_path, sess_options=sessionOptions,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beheerder/Miles-env/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
Python Error: 
  File "/Users/beheerder/Miles-env/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /Users/beheerder/Miles-env/lib/python3.11/site-packages/openwakeword/resources/models/melspectrogram.onnx failed:Load model /Users/beheerder/Miles-env/lib/python3.11/site-packages/openwakeword/resources/models/melspectrogram.onnx failed. File doesn't exist

Python script exited with code: 1
(Miles-env) beheerder@MacBook-Pro Miles-V2 %

**Comment by small-cactus** [comment]
The models for the package are not installed by default. The config python file is supposed to install them for you. Incase it doesn't (probably because it's in a venv). Make a new python file anywhere on your computer, paste this and save and run it:

```
import openwakeword
from openwakeword.model import Model

# One-time download of all pre-trained models (or only select models)
openwakeword.utils.download_models()
```

Once it's done, you can try to run Miles again.

**Comment by small-cactus** [comment]
Try installing tensorflow:

Pip3 install tensorflow

**Comment by jplantenga** [comment]
Yes thanks. Got it working in the mean time, the tensor flow was not being easy getting it installed on a M2 MacBook. Now Ive gotten to the part where MILES is active and listening. Just gotten some new errors on audio handling but this seems more fixable.
